name: Sync image with ImageSyncerTool
on:
  workflow_dispatch:
  schedule:
  - cron: "0 3,15 * * *"

jobs:
  sync-triger:
    runs-on: ubuntu-latest
    steps:
    
    - name: checkout
      uses: actions/checkout@v3
      
    - name: Image Sync Action
      uses: hhyasdf/image-sync-action@v1.1
      with:
        version: latest
        auth_file: ./auth.yaml
        images_file: ./images.yaml
        #arch: amd64
        os: linux
        proc: 100
        retries: 3
      env:
        ALI_PASSWORD: ${{ secrets.ALI_PASSWORD }}
